version: '3.8'
services:
  kafka:
    image: spotify/kafka
    environment:
      ADVERTISED_HOST: 0.0.0.0
      ADVERTISED_PORT: 9092
    ports:
      - 9092:9092
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongodb_data: